// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package buttons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fmt"
import "github.com/go-components/ui/hx"

const (
	VariantDefault     = "default"
	VariantDestructive = "destructive"
	VariantOutline     = "outline"
	VariantSecondary   = "secondary"
	VariantGhost       = "ghost"
	VariantLink        = "link"
	VariantTab         = "tab"

	SizeDefault = "default"
	SizeSm      = "sm"
	SizeLg      = "lg"
	SizeIcon    = "icon"
)

var buttonStyle = map[string]map[string]string{
	"variant": {
		VariantDefault:     "bg-primary text-primary-foreground hover:bg-primary/90",
		VariantDestructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
		VariantOutline:     "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
		VariantSecondary:   "bg-secondary text-secondary-foreground hover:bg-secondary/80",
		VariantGhost:       "hover:bg-accent hover:text-accent-foreground",
		VariantLink:        "text-primary underline-offset-4 hover:underline",
		VariantTab:         "border border-green-600 rounded-b-none bg-green-300 h-6 px-4 font-medium",
	},
	"size": {
		SizeDefault: "h-10 px-4 py-2",
		SizeSm:      "h-9 rounded-md px-3",
		SizeLg:      "h-11 rounded-md px-8",
		SizeIcon:    "h-10 w-10",
	},
}

type ButtonProps struct {
	hx      hx.HX
	href    string
	variant string
	size    string
	_type   string
}

func AsLink(href string) func(*ButtonProps) {
	return func(bp *ButtonProps) { bp.href = href }
}

func Variant(variant string) func(*ButtonProps) {
	return func(bp *ButtonProps) { bp.variant = variant }
}

func Size(size string) func(*ButtonProps) {
	return func(bp *ButtonProps) { bp.size = size }
}

func Submit() func(*ButtonProps) {
	return func(bp *ButtonProps) { bp._type = "submit" }
}

func Hx(opts ...func(hx.HX)) func(*ButtonProps) {
	return func(bp *ButtonProps) { bp.hx = hx.New(opts...) }
}

var buttonClasses = `
inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm
font-medium ring-offset-background transition-colors focus-visible:outline-none
focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2
disabled:pointer-events-none disabled:opacity-50 shadow
`

func Button(options ...func(*ButtonProps)) templ.Component {
	props := &ButtonProps{_type: "button"}
	for _, o := range options {
		o(props)
	}
	if props.variant == "" {
		props.variant = VariantDefault
	}
	if props.size == "" {
		props.size = SizeDefault
	}
	attrs := templ.Attributes{}
	attrs["class"] = fmt.Sprintf("%s %s %s",
		buttonClasses,
		buttonStyle["variant"][props.variant],
		buttonStyle["size"][props.size],
	)
	asLink := props.href != ""
	if asLink {
		attrs["href"] = props.href
	} else {
		attrs["type"] = props._type
	}
	for attr, val := range props.hx {
		attrs[attr] = val
	}
	return button(asLink, attrs)
}

func button(asLink bool, attrs templ.Attributes) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if asLink {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
